import type { Metadata } from "next";
import { Geist, Geist_Mono , Stack_Sans_Text } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer";

const bowby_one_sc = Stack_Sans_Text({
  subsets: ["latin"],
  weight : "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <html
      lang="en"
      className={`${bowby_one_sc.className} h-full antialiased`}
      >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
      <Footer/>
      </>
  );
}
